name: Laravel CI - CRUD Estudiantes

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: crud_estudiantes_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist

      - name: Copiar .env.testing
        run: cp .env.testing .env

      - name: Generar APP_KEY
        run: php artisan key:generate

      - name: Ejecutar migraciones
        run: php artisan migrate --force

      - name: Ejecutar pruebas
        run: php artisan test
